const kurlyDB = [
    {
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },
    {
        src:'./images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:5500,
        sale:20,
        review:18,
    },
    {
        src: './images/kurly_003.jpg',
        name: '[오뚜기] 진한 사골 곰탕 500g',
        summary: '구수한 국물맛이 일품',
        price: 2900,
        sale: 10,
        review: 87,
    },
    {
        src: './images/kurly_004.jpg',
        name: '[서울우유] 딸기우유 200ml',
        summary: '부드럽고 달콤한 딸기맛',
        price: 1200,
        sale: 5,
        review: 132,
    },
    {
        src: './images/kurly_005.jpg',
        name: '[청정원] 햇살 담은 국간장 930ml',
        summary: '요리에 감칠맛을 더하는 간장',
        price: 4100,
        sale: 15,
        review: 45,
    },
    {
        src: './images/kurly_006.jpg',
        name: '[삼양] 불닭볶음면 5입',
        summary: '매운맛을 좋아하는 당신에게',
        price: 4480,
        sale: 8,
        review: 234,
    },
    {
        src: './images/kurly_007.jpg',
        name: '[빙그레] 바나나맛 우유 240ml',
        summary: '누구나 좋아하는 국민 간식',
        price: 1500,
        sale: 0,
        review: 312,
    },
    {
        src: './images/kurly_008.jpg',
        name: '[풀무원] 생가득 물만두 1kg',
        summary: '부드럽고 쫄깃한 만두피',
        price: 7280,
        sale: 12,
        review: 99,
    },
    {
        src: './images/kurly_009.jpg',
        name: '[CJ] 햇반 210g',
        summary: '언제 어디서나 간편하게',
        price: 1800,
        sale: 5,
        review: 278,
    },
    {
        src: './images/kurly_010.jpg',
        name: '[도드람] 한돈 삼겹살 구이용 500g',
        summary: '고소하고 풍미 가득한 삼겹살',
        price: 10900,
        sale: 18,
        review: 56,
    },
    {
        src: './images/kurly_011.jpg',
        name: '[테라] 청정라거 500ml',
        summary: '시원한 라거 맥주의 진수',
        price: 2500,
        sale: 0,
        review: 80,
    },
    {
        src: './images/kurly_012.jpg',
        name: '[롯데] 빠삐코 초코 2입',
        summary: '어릴 적 추억을 담은 아이스크림',
        price: 2200,
        sale: 10,
        review: 163,
    },
]